openapi: 3.0.0
info:
  title: About Me
  description: >
    About Me services for GDI

    - Explore the graphQL endpoint via **https://cloud.hasura.io/public/graphiql?header=content-type:application/json&endpoint=http:{baseUrl}/api/v1/aboutme** (replace baseUrl with actual domain)
  version: 1.0.0
paths:
  /api/v1/{namespace}/healthcheck:
    get:
      operationId: healthCheck
      summary: "Healthcheck of service"
      tags:
        - Status of Operations
      parameters:
        - name: namespace
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Service is healthy"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type:
                      string
  /api/v1/aboutme/send-verification-notification/email:
    post:
      operationId: aboutMeSendEmailVerificationNotification
      summary: Notify user with a link for verifying their email adress
      tags:
        - Contact details verification
      security:
        - BearerAuth: []
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendVerificationResponse'
  /api/v1/aboutme/send-verification-notification/phone:
    post:
      operationId: aboutMeSendPhoneVerificationNotification
      summary: Notify user with a link for verifying their phone number
      tags:
        - Contact details verification
      security:
        - BearerAuth: []
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendVerificationResponse'

  /api/v1/aboutme/verify/email/{verificationCode}:
    get:
      operationId: aboutMeVerifyEmail
      summary: 'Verify user submitted email details given verification code'
      tags:
        - Contact details verification
      parameters:
        - in: path
          name: verificationCode
          schema:
            type: string
          required: true
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerificationResponse'
  /api/v1/aboutme/verify/phone/{verificationCode}:
    get:
      operationId: aboutMeVerifyPhone
      summary: 'Verify user submitted phone details given verification code'
      tags:
        - Contact details verification
      parameters:
        - in: path
          name: verificationCode
          schema:
            type: string
          required: true
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerificationResponse'
  /api/v1/aboutme/graphql:
    post:
      operationId: aboutMeGql
      summary: "GraphQL endpoint for About Me"
      tags:
        - About Me
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GraphQLQuery"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GraphQLResponse"
components:
  securitySchemes:
      BearerAuth:
        type: http
        scheme: bearer
  schemas:
    VerificationResponse:
      type: object
      properties:
        verified:
          type: boolean
    SendVerificationResponse:
      type: object
      properties:
        success:
          type: boolean
    GraphQLQuery:
      type: object
      required:
        - query
      properties:
        query:
          type: string
        parameters:
          type: object
    GraphQLResponse:
      type: object
      properties:
        data:
          type: object


