openapi: 3.0.0
info:
  title: About Me
  description: About Me services for GDI
  version: 1.0.0
tags:
  - name: Web authentication
    description: Authentication operations
paths:
  /api/v1/aboutme/graphql:
    post:
      operationId: aboutMeGql
      summary: "GraphQL endpoint for About Me"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GraphQLQuery"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GraphQLResponse"
components:
  schemas:
    GraphQLQuery:
      type: object
      required:
        - query
      properties:
        query:
          type: string
        parameters:
          type: object
    GraphQLResponse:
      type: object
      properties:
        data:
          type: object